### ISSUE TITLE
Consider adding SIM selection

### ISSUE THREAD

**Issue by hbmartin** [jump-sdk/jetpack_compose_country_code_picker_emoji#19]
https://proandroiddev.com/phone-number-hint-api-in-jetpack-compose-e164a612f44f

**Comment by ankur2136** [comment]
@hbmartin Is this something you have plans to work on? 
Otherwise I was thinking I can add this feature.

**Comment by hbmartin** [comment]
https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/pull/49
