### ISSUE TITLE
Cannot access class 'androidx.compose.material.TextFieldColors'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by dyazincahya** [jump-sdk/jetpack_compose_country_code_picker_emoji#23]
**Describe the bug**
I have an error like this ```Cannot access class 'androidx.compose.material.TextFieldColors'. Check your module classpath for missing or conflicting dependencies``` 

**Spec**
- androidx.core:core-ktx:1.12.0
- androidx.compose.material3:material3

![image](https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/assets/5259738/877fbd42-5a8c-4680-9ffd-f255289247ac)

**Comment by hbmartin** [comment]
Hi @dyazincahya , I suspect this is due to conflicting versions of compose (specifically `androidx.compose.material:material` in this case) which is currently being built with 1.5.0 https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/blob/master/gradle/libs.versions.toml#L21
Can you see if changing this dependency version fixes the issue?

**Comment by hbmartin** [comment]
Note that in the 2.1.1 release Compose was upgraded to 1.5.1

Closing this now, feel free to reopen if the problem persists after applying the above suggestion.

**Comment by waheedkhan-dev** [comment]
Hi @hbmartin I am facing the same issue

**Comment by hbmartin** [comment]
@waheedkhan-dev what Compose version are you using?

**Comment by cw-communiski** [comment]
I had this problem using Material3 - I added Material2 as well and this issue went away:

    implementation("androidx.compose.material:material:1.5.2")

(I still can't get it to build though as I'm getting other errors)

**Comment by hbmartin** [comment]
@cw-communiski can you post of log of the other build errors?

**Comment by waheedkhan-dev** [comment]
@hbmartin 
![image](https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/assets/55230825/cc34b0af-3827-4d03-9d0f-551317e888bc)
![image](https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/assets/55230825/4936aebe-4113-433a-b86c-6d0d823be978)

![Uploading image.png…]()

**Comment by dyazincahya** [comment]
> Note that in the 2.1.1 release Compose was upgraded to 1.5.1
> 
> Closing this now, feel free to reopen if the problem persists after applying the above suggestion.

Thank you @hbmartin :fire:

**Comment by waheedkhan-dev** [comment]
I have add the material 2 dependency the error gone but now i want to change the background color of text field but it also change the country dialog background color as well

![image](https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/assets/55230825/3029c36c-1006-4e42-a342-05f3042cf354)

![image](https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/assets/55230825/15147530-1167-462e-bb6b-39d537248fd8)

![image](https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/assets/55230825/9a7acc8e-d36e-4f65-a445-17aeba2af381)
