### ISSUE TITLE
More publicly available features through library

### ISSUE THREAD

**Issue by ali0399** [jump-sdk/jetpack_compose_country_code_picker_emoji#24]
When using the library only TogiCountryCodePicker is available to use which is an integrated component with country indicator, text field and dialog.

It would be more versatile and universal if you can make seperate components public. Like the TogiCodeDialog can be made available for someone who wants to implement the text field separately. Also the country data can be made public so that more customised stuff can be made and also future updates to the country list can be more easily updated to any project.

i have tried to use the CCP module directly in my projects and did my customisations there.

**Comment by hbmartin** [comment]
Hi @ali0399 thanks for the comment. Can you list the specific classes you need for your project?

**Comment by hbmartin** [comment]
Country picker UI and CountryData will be exposed in 2.2.0 release once we merge https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/pull/32
Please comment and reopen if this does not meet your needs!

**Comment by hbmartin** [comment]
@ali0399 2.2.0 is now released, please feel free to add further suggestions in a new issue.
