### ISSUE TITLE
Add possibility to pass a text into composable 

### ISSUE THREAD

**Issue by Alexbeard** [jump-sdk/jetpack_compose_country_code_picker_emoji#25]
You lost one of the main features of this library, we are not able to pass the phone number for the textfield. 
This may be useful for screens like "edit profile" where people can change their **existing** phone to another one, for now this is not possible

**Comment by hbmartin** [comment]
@Alexbeard this is now available in the 2.2.0 release

**Comment by Alexbeard** [comment]
Nice, thank you, I will try
