### ISSUE TITLE
Change the border colour of the container

### ISSUE THREAD

**Issue by HowardRHard** [jump-sdk/jetpack_compose_country_code_picker_emoji#57]
I have tried looking through the information available on this GitHub repo but can't seem to find this, if it already exists please point me in the right direction.

Put simply I need to change the colour of the container in the unused, error and being used state, let me know if this is a possibility or where I could look into it myself

**Comment by hbmartin** [comment]
Hi @HowardRHard 👋 You can do this by setting the relevant `*BorderColor` parameters when calling [TextFieldDefaults.outlinedTextFieldColors(...)](https://developer.android.com/reference/kotlin/androidx/compose/material/TextFieldDefaults#outlinedTextFieldColors(androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color)) and passing that to the picker's `colors` parameter
